[package]
name = "wat_parser"
version = "0.1.0"
authors = ["Antoine D <antoine.desbordes@gmail.com>"]

[dependencies]
log = "0.4"
env_logger = "0.5.0-rc.1"
structopt = "0.2"
failure = "*"
regex = "*"
json = "*"
serde_json = "*"
serde_derive = "*"
serde = "*"
cassandra-cpp = "*"
futures = "*"
